<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log; // Import Log explicitly

class BackupDatabase extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:backup-database';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Backup the database';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info('Starting database backup...');
        
        try {
            $connection = config('database.default');
            $this->info("Current Database Driver: " . $connection);

            $extension = ($connection === 'sqlite') ? '.sqlite' : '.sql';
            $filename = 'backup-' . date('Y-m-d-H-i-s') . $extension;
            $path = storage_path('app/backups/' . $filename);
            
            // Ensure backups directory exists
            if (!file_exists(storage_path('app/backups'))) {
                mkdir(storage_path('app/backups'), 0755, true);
            }

            if ($connection === 'sqlite') {
                $this->backupSqlite($path);
            } elseif ($connection === 'mysql') {
                $this->backupMysql($path);
            } else {
                $this->error("Database driver '$connection' not supported for backup.");
                return;
            }

            // Calculate size
            $sizeBytes = file_exists($path) ? filesize($path) : 0;
            $size = $this->formatSize($sizeBytes);

             // Save to DB via Query Builder (Safer)
            \Illuminate\Support\Facades\DB::table('database_backups')->insert([
                'filename' => $filename,
                'path' => 'backups/' . $filename,
                'size' => $size,
                'status' => 'completed',
                'created_by' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            $this->info("Backup completed: $filename ($size)");

        } catch (\Throwable $e) {
            $this->error("Backup failed: " . $e->getMessage());
            Log::error("Backup fatal error: " . $e->getMessage());
            if (isset($path) && file_exists($path)) {
                @unlink($path); // Cleanup failed file
            }
        }
    }

    private function backupSqlite($destination)
    {
        $source = config('database.connections.sqlite.database');
        
        // Handle if configured as absolute path or relative
        if (!file_exists($source)) {
             // Try database_path helper if simple string
             $source = database_path($source);
        }

        if (!file_exists($source)) {
            throw new \Exception("SQLite database file not found at: $source");
        }
        
        if (!copy($source, $destination)) {
            throw new \Exception("Failed to copy SQLite file.");
        }
    }

    private function backupMysql($path) {
        $username = config('database.connections.mysql.username');
        $password = config('database.connections.mysql.password');
        $database = config('database.connections.mysql.database');
        $host = config('database.connections.mysql.host');
        $port = config('database.connections.mysql.port');

        if ($host === 'localhost') $host = '127.0.0.1';

        $command = sprintf(
            'mysqldump --user=%s --password=%s --host=%s --port=%s --protocol=tcp %s > "%s"',
            escapeshellarg($username),
            escapeshellarg($password),
            escapeshellarg($host),
            escapeshellarg($port),
            escapeshellarg($database),
            $path
        );

        $returnVar = null;
        $output = [];
        exec($command, $output, $returnVar);

        if ($returnVar !== 0) {
            $this->warn('mysqldump failed, attempting PHP-based backup fallback...');
            $this->backupMysqlFallback($path);
        }
    }

    private function backupMysqlFallback($path)
    {
        $handle = fopen($path, 'w');
        if (!$handle) throw new \Exception("Cannot open file: $path");

        try {
            $tables = \Illuminate\Support\Facades\DB::select('SHOW TABLES');
            $dbName = config('database.connections.mysql.database');
            
            fwrite($handle, "-- Backup Generated by System at " . date('Y-m-d H:i:s') . "\n\n");
            fwrite($handle, "SET FOREIGN_KEY_CHECKS=0;\n\n");

            foreach ($tables as $table) {
                $tableArray = (array)$table;
                $tableName = array_values($tableArray)[0];
                
                $this->info("Backing up table: $tableName");

                $createTable = \Illuminate\Support\Facades\DB::select("SHOW CREATE TABLE `$tableName`");
                $createTableArray = (array)$createTable[0];
                $createSql = $createTableArray['Create Table'];
                
                fwrite($handle, "DROP TABLE IF EXISTS `$tableName`;\n");
                fwrite($handle, $createSql . ";\n\n");

                foreach (\Illuminate\Support\Facades\DB::table($tableName)->cursor() as $row) {
                     $values = array_map(function ($value) {
                        return is_null($value) ? "NULL" : "'" . addslashes($value) . "'";
                    }, (array)$row);
                    $sql = "INSERT INTO `$tableName` VALUES (" . implode(', ', $values) . ");\n";
                    fwrite($handle, $sql);
                }
                fwrite($handle, "\n");
            }

            fwrite($handle, "SET FOREIGN_KEY_CHECKS=1;\n");
        } finally {
            fclose($handle);
        }
    }

    private function formatSize($bytes)
    {
        if ($bytes >= 1073741824) {
            return number_format($bytes / 1073741824, 2) . ' GB';
        } elseif ($bytes >= 1048576) {
            return number_format($bytes / 1048576, 2) . ' MB';
        } elseif ($bytes >= 1024) {
            return number_format($bytes / 1024, 2) . ' KB';
        } elseif ($bytes > 1) {
            return $bytes . ' bytes';
        } elseif ($bytes == 1) {
            return $bytes . ' byte';
        } else {
            return '0 bytes';
        }
    }
}
